### ISSUE TITLE
两点感觉不太好的地方

### ISSUE THREAD

**Issue by darkfiredarkhalo** [accforgit/react-native-modal-alert#1]
1,对组件侵入太多.不能像系统组件一样使用,需要在render的时候加载;
2,未对安卓的物理返回进行拦截:modal的视图在安卓上是可以通过返回键退出的,而alert是不允许这么做的

**Comment by accforgit** [comment]
1. 确实侵入了组件，但毕竟不是系统组件，只是一层封装，想要像系统组件那样使用有些困难
2. 是否需要对安卓的物理返回键进行拦截，无论是是还是否都各有应用场景，欢迎发起pull
